//
//  Enums.LanguagePairs.swift
//  sugah
//
//  Created by Rodi on 2/6/23.
//

import Foundation
import BackgroundTasks

let languageCodePairs: [String: [String]] = [
    "aa": ["Afar", "Afaraf"],
    "ab": ["Abkhazian", "Аҧсуа бызшәа, аҧсшәа"],
    "ae": ["Avestan", "avesta"],
    "af": ["Afrikaans", "Afrikaans"],
    "ak": ["Akan", "Akan"],
    "am": ["Amharic", "አማርኛ"],
    "an": ["Aragonese", "aragonés"],
    "ar": ["Arabic", "العربية"],
    "as": ["Assamese", "অসমীয়া"],
    "av": ["Avaric", "авар мацӀ, магӀарул мацӀ"],
    "ay": ["Aymara", "aymar aru"],
    "az": ["Azerbaijani", "azərbaycan dili"],
    "ba": ["Bashkir", "башҡорт теле"],
    "be": ["Belarusian", "беларуская мова"],
    "bg": ["Bulgarian", "български език"],
    "bh": ["Bihari", "भोजपुरी"],
    "bi": ["Bislama", "Bislama"],
    "bm": ["Bambara", "bamanankan"],
    "bn": ["Bengali, Bangla", "বাংলা"],
    "bo": ["Tibetan Standard, Tibetan, Central", "བོད་ཡིག"],
    "br": ["Breton", "brezhoneg"],
    "bs": ["Bosnian", "bosanski jezik"],
    "ca": ["Catalan", "Català"],
    "ce": ["Chechen", "нохчийн мотт"],
    "ch": ["Chamorro", "Chamoru"],
    "co": ["Corsican", "corsu, lingua corsa"],
    "cr": ["Cree", "ᓀᐦᐃᔭᐍᐏᐣ"],
    "cs": ["Czech", "čeština, český jazyk"],
    "cu": ["Old Church Slavonic, Church Slavonic, Old Bulgarian", "ѩзыкъ словѣньскъ"],
    "cv": ["Chuvash", "чӑваш чӗлхи"],
    "cy": ["Welsh", "Cymraeg"],
    "da": ["Danish", "dansk"],
    "de": ["German", "Deutsch"],
    "dv": ["Divehi, Dhivehi, Maldivian", "ދިވެހި"],
    "dz": ["Dzongkha", "རྫོང་ཁ"],
    "ee": ["Ewe", "Eʋegbe"],
    "el": ["Greek (modern)", "ελληνικά"],
    "en": ["English", "English"],
    "eo": ["Esperanto", "Esperanto"],
    "es": ["Spanish", "Español, Castellano"],
    "et": ["Estonian", "Eesti keel"],
    "eu": ["Basque", "Euskara, Euskera"],
    "fa": ["Persian", "فارسی"],
    "ff": ["Fula", "Fulfulde, Pulaar, Pular"],
    "fi": ["Finnish", "Suomi, Suomen kieli"],
    "fj": ["Fijian", "Vosa Vakaviti"],
    "fo": ["Faroese", "Føroyskt"],
    "fr": ["French", "Français, Langue Française"],
    "fy": ["Western Frisian", "Frysk"],
    "ga": ["Irish", "Gaeilge"],
    "gd": ["Scottish Gaelic", "Gàidhlig"],
    "gl": ["Galician", "Galego"],
    "gn": ["Guaraní", "Avañe'ẽ"],
    "gu": ["Gujarati", "ગુજરાતી"],
    "gv": ["Manx", "Gaelg, Gailck"],
    "ha": ["Hausa", "Hausa, هَوُسَ"],
    "he": ["Hebrew", "עברית"],
    "hi": ["Hindi", "हिन्दी, हिंदी"],
    "ho": ["Hiri Motu", "Hiri Motu"],
    "hr": ["Croatian", "Hrvatski"],
    "ht": ["Haitian", "Kreyòl ayisyen"],
    "hu": ["Hungarian", "Magyar"],
    "hy": ["Armenian", "Հայերեն"],
    "hz": ["Herero", "Otjiherero"],
    "ia": ["Interlingua", "Interlingua"],
    "id": ["Indonesian", "Bahasa Indonesia"],
    "ie": ["Interlingue", "Originally Called Occidental; Then Interlingue After WWII"],
    "ig": ["Igbo", "Asụsụ Igbo"],
    "ii": ["Nuosu", "ꆈꌠ꒿ Nuosuhxop"],
    "ik": ["Inupiaq", "Iñupiaq, Iñupiatun"],
    "io": ["Ido", "Ido"],
    "is": ["Icelandic", "Íslenska"],
    "it": ["Italian", "Italiano"],
    "iu": ["Inuktitut", "ᐃᓄᒃᑎᑐᑦ"],
    "ja": ["Japanese", "日本語"],
    "jv": ["Javanese", "basa Jawa"],
    "ka": ["Georgian", "ქართული"],
    "kg": ["Kongo", "KiKongo"],
    "ki": ["Kikuyu", "Gĩkũyũ"],
    "kj": ["Kwanyama", "Kuanyama"],
    "kk": ["Kazakh", "Қазақ тілі"],
    "kl": ["Kalaallisut", "kalaallisut, kalaallit oqaasii"],
    "km": ["Khmer", "ភាសាខ្មែរ"],
    "kn": ["Kannada", "ಕನ್ನಡ"],
    "ko": ["Korean", "한국어"],
    "kr": ["Kanuri", "Kanuri"],
    "ks": ["Kashmiri", "कश्मीरी, كشميري‎"],
    "ku": ["Kurdish", "Kurdî, كوردی‎"],
    "kv": ["Komi", "коми кыв"],
    "kw": ["Cornish", "Kernewek"],
    "ky": ["Kirghiz", "Кыргызча, Кыргыз тили"],
    "la": ["Latin", "latine, lingua latina"],
    "lb": ["Luxembourgish", "Lëtzebuergesch"],
    "lg": ["Ganda", "Luganda"],
    "li": ["Limburgish", "Limburgs"],
    "ln": ["Lingala", "Lingála"],
    "lo": ["Lao", "ພາສາລາວ"],
    "lt": ["Lithuanian", "lietuvių kalba"],
    "lu": ["Luba-Katanga", "Luba-Katanga"],
    "lv": ["Latvian", "latviešu valoda"],
    "mg": ["Malagasy", "fiteny malagasy"],
    "mh": ["Marshallese", "Kajin M̧ajeļ"],
    "mi": ["Māori", "te reo Māori"],
    "mk": ["Macedonian", "македонски јазик"],
    "ml": ["Malayalam", "മലയാളം"],
    "mn": ["Mongolian", "Монгол хэл"],
    "mr": ["Marathi", "मराठी"],
    "ms": ["Malay", "bahasa Melayu, بهاس ملايو‎"],
    "mt": ["Maltese", "Malti"],
    "my": ["Burmese", "ဗမာစာ"],
    "na": ["Nauru", "Ekakairũ Naoero"],
    "nb": ["Norwegian Bokmål", "Norsk bokmål"],
    "nd": ["North Ndebele", "isiNdebele"],
    "ne": ["Nepali", "नेपाली"],
    "ng": ["Ndonga", "Owambo"],
    "nl": ["Dutch", "Nederlands, Vlaams"],
    "nn": ["Norwegian Nynorsk", "Norsk nynorsk"],
    "no": ["Norwegian", "Norsk"],
    "nr": ["South Ndebele", "isiNdebele"],
    "nv": ["Navajo", "Diné bizaad"],
    "ny": ["Chichewa", "chiCheŵa, chinyanja"],
    "oc": ["Occitan", "Occitan"],
    "oj": ["Ojibwe, Ojibwa", "ᐊᓂᔑᓈᓇᐯᒧᐎᓐ"],
    "om": ["Oromo", "Afaan Oromoo"],
    "or": ["Oriya", "ଓଡ଼ିଆ"],
    "os": ["Ossetian, Ossetic", "Ирон æвзаг"],
    "pa": ["Punjabi, Panjabi", "ਪੰਜਾਬੀ, پنجابی‎"],
    "pi": ["Pali", "पाऴि"],
    "pl": ["Polish", "polski"],
    "ps": ["Pashto, Pushto", "پښتو"],
    "pt": ["Portuguese", "Português"],
    "qu": ["Quechua", "Runa Simi, Kichwa"],
    "rm": ["Romansh", "rumantsch grischun"],
    "rn": ["Kirundi", "kiRundi"],
    "ro": ["Romanian, Moldavian, Moldovan", "română"],
    "ru": ["Russian", "русский язык"],
    "rw": ["Kinyarwanda", "Ikinyarwanda"],
    "sa": ["Sanskrit (Saṁskṛta)", "संस्कृतम्"],
    "sc": ["Sardinian", "sardu"],
    "sd": ["Sindhi", "सिन्धी, سنڌي، سندھی‎"],
    "se": ["Northern Sami", "Davvisámegiella"],
    "sg": ["Sango", "yângâ tî sängö"],
    "si": ["Sinhalese, Sinhala", "සිංහල"],
    "sk": ["Slovak", "slovenčina"],
    "sl": ["Slovene", "slovenski jezik"],
    "sm": ["Samoan", "gagana fa'a Samoa"],
    "sn": ["Shona", "chiShona"],
    "so": ["Somali", "Soomaaliga, af Soomaali"],
    "sq": ["Albanian", "Shqip"],
    "sr": ["Serbian", "српски језик"],
    "ss": ["Swati", "SiSwati"],
    "st": ["Southern Sotho", "Sesotho"],
    "su": ["Sundanese", "Basa Sunda"],
    "sv": ["Swedish", "svenska"],
    "sw": ["Swahili", "Kiswahili"],
    "ta": ["Tamil", "தமிழ்"],
    "te": ["Telugu", "తెలుగు"],
    "tg": ["Tajik", "тоҷикӣ, toğikī, تاجیکی‎"],
    "th": ["Thai", "ไทย"],
    "ti": ["Tigrinya", "ትግርኛ"],
    "tig": ["Tigre", "ትግረ"],
    "tk": ["Turkmen", "Türkmen, Түркмен"],
    "tl": ["Tagalog", "Wikang Tagalog"],
    "tn": ["Tswana", "Setswana"],
    "to": ["Tonga (Tonga Islands)", "Faka Tonga"],
    "tr": ["Turkish", "Türkçe"],
    "ts": ["Tsonga", "Xitsonga"],
    "tt": ["Tatar", "Татар теле"],
    "tw": ["Twi", "Twi"],
    "ty": ["Tahitian", "Reo Tahiti"],
    "ug": ["Uighur", "ئۇيغۇر تىلى"],
    "uk": ["Ukrainian", "Українська"],
    "ur": ["Urdu", "اردو"],
    "uz": ["Uzbek", "O‘zbek, Ўзбек, أۇزبېك‎"],
    "ve": ["Venda", "Tshivenḓa"],
    "vi": ["Vietnamese", "Tiếng Việt"],
    "vo": ["Volapük", "Volapük"],
    "wa": ["Walloon", "Walon"],
    "wo": ["Wolof", "Wollof"],
    "xh": ["Xhosa", "isiXhosa"],
    "yi": ["Yiddish", "ייִדיש"],
    "yo": ["Yoruba", "Yorùbá"],
    "za": ["Zhuang, Chuang", "Saɯ cueŋƅ, Saw cuengh"],
    "zh": ["Chinese", "中文 (Zhōngwén), 汉语, 漢語"],
    "zu": ["Zulu", "isiZulu"]    ]
    
    
let languageNamePairs: [String: (englishName: String, nativeName: String)] = [
    
//    let urduPair = languageNamePairs["ur"]
//    This will assign the tuple value ("Urdu", "اردو") to the urduPair constant.
    //    You can then access the individual elements of the tuple using dot notation, like this:
    //
    //    print(urduPair?.englishName)  // prints "Urdu"
    //    print(urduPair?.nativeName)   // prints "اردو"
    
    "aa": ("Afar", "Afaraf"),
    "ab": ("Abkhazian", "Аҧсуа бызшәа, аҧсшәа"),
    "ae": ("Avestan", "avesta"),
    "af": ("Afrikaans", "Afrikaans"),
    "ak": ("Akan", "Akan"),
    "am": ("Amharic", "አማርኛ"),
    "an": ("Aragonese", "aragonés"),
    "ar": ("Arabic", "العربية"),
    "as": ("Assamese", "অসমীয়া"),
    "av": ("Avaric", "авар мацӀ, магӀарул мацӀ"),
    "ay": ("Aymara", "aymar aru"),
    "az": ("Azerbaijani", "azərbaycan dili"),
    "ba": ("Bashkir", "башҡорт теле"),
    "be": ("Belarusian", "беларуская мова"),
    "bg": ("Bulgarian", "български език"),
    "bh": ("Bihari", "भोजपुरी"),
    "bi": ("Bislama", "Bislama"),
    "bm": ("Bambara", "bamanankan"),
    "bn": ("Bengali", "বাংলা"),
    "bo": ("Tibetan", "བོད་ཡིག"),
    "br": ("Breton", "brezhoneg"),
    "bs": ("Bosnian", "bosanski jezik"),
    "ca": ("Catalan", "català"),
    "ce": ("Chechen", "нохчийн мотт"),
    "ch": ("Chamorro", "Chamoru"),
    "co": ("Corsican", "corsu, lingua corsa"),
    "cr": ("Cree", "ᓀᐦᐃᔭᐍᐏᐣ"),
    "cs": ("Czech", "čeština, český jazyk"),
    "cu": ("Church Slavic", "ѩзыкъ словѣньскъ"),
    "cv": ("Chuvash", "чӑваш чӗлхи"),
    "cy": ("Welsh", "Cymraeg"),
    "da": ("Danish", "dansk"),
    "de": ("German", "Deutsch"),
    "dv": ("Divehi", "ދިވެހި"),
    "dz": ("Dzongkha", "རྫོང་ཁ"),
    "ee": ("Ewe", "Eʋegbe"),
    "el": ("Greek", "Ελληνικά"),
    "en": ("English", "English"),
    "eo": ("Esperanto", "Esperanto"),
    "es": ("Spanish", "español"),
    "et": ("Estonian", "eesti, eesti keel"),
    "eu": ("Basque", "euskara, euskera"),
    "fa": ("Persian", "فارسی"),
    "ff": ("Fulah", "Fulfulde, Pulaar, Pular"),
    "fi": ("Finnish", "suomi, suomen kieli"),
    "fj": ("Fijian", "vosa Vakaviti"),
    "fo": ("Faroese", "føroyskt"),
    "fr": ("French", "français"),
    "fy": ("Western Frisian", "Frysk"),
    "ga": ("Irish", "Gaeilge"),
    "gd": ("Scottish Gaelic", "Gàidhlig"),
    "gl": ("Galician", "galego"),
    "gn": ("Guarani", "Avañe'ẽ"),
    "gu": ("Gujarati", "ગુજરાતી"),
    "gv": ("Manx", "Gaelg, Gailck"),
    "ha": ("Hausa", "Hausa, هَوُسَ"),
    "he": ("Hebrew", "עברית"),
    "hi": ("Hindi", "हिन्दी, हिंदी"),
    "ho": ("Hiri Motu", "Hiri Motu"),
    "hr": ("Croatian", "hrvatski jezik"),
    "ht": ("Haitian", "Kreyòl ayisyen"),
    "hu": ("Hungarian", "magyar"),
    "hy": ("Armenian", "Հայերեն"),
    "hz": ("Herero", "Otjiherero"),
    "ia": ("Interlingua", "Interlingua"),
    "id": ("Indonesian", "Bahasa Indonesia"),
    "ie": ("Interlingue", "Interlingue"),
    "ig": ("Igbo", "Asụsụ Igbo"),
    "ii": ("Sichuan Yi", "ꆈꌠ꒿ Nuosuhxop"),
    "ik": ("Inupiaq", "Iñupiaq, Iñupiatun"),
    "io": ("Ido", "Ido"),
    "is": ("Icelandic", "íslenska"),
    "it": ("Italian", "italiano"),
    "iu": ("Inuktitut", "ᐃᓄᒃᑎᑐᑦ"),
    "ja": ("Japanese", "日本語"),
    "jv": ("Javanese", "basa Jawa"),
    "ka": ("Georgian", "ქართული"),
    "kg": ("Kongo", "KiKongo"),
    "ki": ("Kikuyu", "Gĩkũyũ"),
    "kj": ("Kuanyama", "Kuanyama"),
    "kk": ("Kazakh", "қазақ тілі"),
    "kl": ("Kalaallisut", "kalaallisut, kalaallit oqaasii"),
    "km": ("Khmer", "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ"),
    "kn": ("Kannada", "ಕನ್ನಡ"),
    "ko": ("Korean", "한국어"),
    "kr": ("Kanuri", "Kanuri"),
    "ks": ("Kashmiri", "कश्मीरी, كشميري‎"),
    "ku": ("Kurdish", "Kurdî, كوردی‎"),
    "kv": ("Komi", "коми кыв"),
    "kw": ("Cornish", "Kernewek"),
    "ky": ("Kirghiz", "кыргыз тили"),
    "la": ("Latin", "latine, lingua latina"),
    "lb": ("Luxembourgish", "Lëtzebuergesch"),
    "lg": ("Ganda", "Luganda"),
    "li": ("Limburgish", "Limburgs"),
    "ln": ("Lingala", "Lingála"),
    "lo": ("Lao", "ພາສາລາວ"),
    "lt": ("Lithuanian", "lietuvių kalba"),
    "lu": ("Luba-Katanga", "Tshiluba"),
    "lv": ("Latvian", "latviešu valoda"),
    "mg": ("Malagasy", "Malagasy fiteny"),
    "mh": ("Marshallese", "Kajin M̧ajeļ"),
    "mi": ("Māori", "te reo Māori"),
    "mk": ("Macedonian", "македонски јазик"),
    "ml": ("Malayalam", "മലയാളം"),
    "mn": ("Mongolian", "Монгол хэл"),
    "mo": ("Moldavian", "limba moldovenească"),
    "mr": ("Marathi", "मराठी"),
    "ms": ("Malay", "bahasa Melayu, بهاس ملايو‎"),
    "mt": ("Maltese", "Malti"),
    "my": ("Burmese", "ဗမာစာ"),
    "na": ("Nauru", "Ekakairũ Naoero"),
    "nb": ("Norwegian Bokmål", "Norsk bokmål"),
    "nd": ("North Ndebele", "isiNdebele"),
    "ne": ("Nepali", "नेपाली"),
    "ng": ("Ndonga", "Owambo"),
    "nl": ("Dutch", "Nederlands"),
    "nn": ("Norwegian Nynorsk", "Norsk nynorsk"),
    "no": ("Norwegian", "Norsk"),
    "nr": ("South Ndebele", "isiNdebele"),
    "nv": ("Navajo", "Diné bizaad, Dinékʼehǰí"),
    "ny": ("Chichewa", "chiCheŵa, chinyanja"),
    "oc": ("Occitan", "occitan, lenga d'òc"),
    "oj": ("Ojibwa", "ᐊᓂᔑᓈᐯᒧᐎᓐ"),
    "om": ("Oromo", "Afaan Oromoo"),
    "or": ("Oriya", "ଓଡ଼ିଆ"),
    "os": ("Ossetian", "ирон æвзаг"),
    "pa": ("Panjabi", "ਪੰਜਾਬੀ, پنجابی‎"),
    "pi": ("Pāli", "पाऴि"),
    "pl": ("Polish", "język polski, polszczyzna"),
    "ps": ("Pashto", "پښتو"),
    "pt": ("Portuguese", "português"),
    "qu": ("Quechua", "Runa Simi, Kichwa"),
    "rm": ("Romansh", "rumantsch grischun"),
    "rn": ("Rundi", "Ikirundi"),
    "ro": ("Romanian", "limba română"),
    "ru": ("Russian", "русский язык"),
    "rw": ("Kinyarwanda", "Ikinyarwanda"),
    "sa": ("Sanskrit", "संस्कृतम्"),
    "sc": ("Sardinian", "sardu"),
    "sd": ("Sindhi", "सिन्धी, سنڌي، سندھی‎"),
    "se": ("Northern Sami", "Davvisámegiella"),
    "sg": ("Sango", "yângâ tî sängö"),
    "si": ("Sinhala", "සිංහල"),
    "sk": ("Slovak", "slovenčina, slovenský jazyk"),
    "sl": ("Slovenian", "slovenski jezik, slovenščina"),
    "sm": ("Samoan", "gagana fa'a Samoa"),
    "sn": ("Shona", "chiShona"),
    "so": ("Somali", "Soomaaliga, af Soomaali"),
    "sq": ("Albanian", "shqip"),
    "sr": ("Serbian", "српски језик"),
    "ss": ("Swati", "SiSwati"),
    "st": ("Southern Sotho", "Sesotho"),
    "su": ("Sundanese", "Basa Sunda"),
    "sv": ("Swedish", "svenska"),
    "sw": ("Swahili", "Kiswahili"),
    "ta": ("Tamil", "தமிழ்"),
    "te": ("Telugu", "తెలుగు"),
    "tg": ("Tajik", "тоҷикӣ, toğikī, تاجیکی‎"),
    "th": ("Thai", "ไทย"),
    "ti": ("Tigrinya", "ትግርኛ"),
    "tk": ("Turkmen", "Türkmen, Түркмен"),
    "tl": ("Tagalog", "Wikang Tagalog"),
    "tn": ("Tswana", "Setswana"),
    "to": ("Tonga", "faka Tonga"),
    "tr": ("Turkish", "Türkçe"),
    "ts": ("Tsonga", "Xitsonga"),
    "tt": ("Tatar", "татар теле, tatar tele"),
    "tw": ("Twi", "Twi"),
    "ty": ("Tahitian", "Reo Tahiti"),
    "ug": ("Uighur", "Uyƣurqə, ئۇيغۇرچە‎"),
    "uk": ("Ukrainian", "українська мова"),
    "ur": ("Urdu", "اردو"),
    "uz": ("Uzbek", "Oʻzbek, Ўзбек, أۇزبېك‎"),
    "ve": ("Venda", "Tshivenḓa"),
    "vi": ("Vietnamese", "Tiếng Việt"),
    "vo": ("Volapük", "Volapük"),
    "wa": ("Walloon", "walon"),
    "wo": ("Wolof", "Wollof"),
    "xh": ("Xhosa", "isiXhosa"),
    "yi": ("Yiddish", "ייִדיש"),
    "yo": ("Yoruba", "Yorùbá"),
    "za": ("Zhuang", "Saɯ cueŋƅ, Saw cuengh"),
    "zh": ("Chinese", "中文 (Zhōngwén), 汉语, 漢語"),
    "zu": ("Zulu", "isiZulu")
    
    
    
    ]

let regionCodes: [String: String] = [
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "American Samoa": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarctica": "AQ",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Aruba": "AW",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "British Indian Ocean Territory": "IO",
    "British Virgin Islands": "VG",
    "Brunei": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde": "CV",
    "Cayman Islands": "KY",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Christmas Island": "CX",
    "Cocos Islands": "CC",
    "Colombia": "CO",
    "Comoros": "KM",
    "Cook Islands": "CK",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Curacao": "CW",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Democratic Republic of the Congo": "CD",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "East Timor": "TL",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Ethiopia": "ET",
    "Falkland Islands": "FK",
    "Faroe Islands": "FO",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "French Polynesia": "PF",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Greece": "GR",
    "Greenland": "GL",
    "Grenada": "GD",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Heard Island and McDonald Islands": "HM",
    "Holy See (Vatican City State)": "VA",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran, Islamic Republic of": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Isle of Man": "IM",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jersey": "JE",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Korea, Democratic People's Republic of": "KP",
    "Korea, Republic of": "KR",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Lao People's Democratic Republic": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macao": "MO",
    "North Macedonia": "MK",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Martinique": "MQ",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexico": "MX",
    "Micronesia, Federated States of": "FM",
    "Moldova, Republic of": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Montserrat": "MS",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Norfolk Island": "NF",
    "Northern Mariana Islands": "MP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Palestine, State of": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Pitcairn Islands": "PN",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Réunion": "RE",
    "Romania": "RO",
    "Russia": "RU",
    "Rwanda": "RW",
    "Saint Barthélemy": "BL",
    "Saint Helena": "SH",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Martin": "MF",
    "Saint Pierre and Miquelon": "PM",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "São Tomé and Príncipe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Sint Maarten": "SX",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Georgia and the South Sandwich Islands": "GS",
    "South Korea": "KR",
    "South Sudan": "SS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Svalbard and Jan Mayen": "SJ",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syria": "SY",
    "Taiwan": "TW",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Turks and Caicos Islands": "TC",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "United States Minor Outlying Islands": "UM",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Virgin Islands, British": "VG",
    "Virgin Islands, U.S.": "VI",
    "Wallis and Futuna": "WF",
    "Western Sahara": "EH",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
    ]
    





    let languageRegions: [LanguageCode: [String]] = [
    .l_aa: ["Djibouti", "Eritrea", "Ethiopia", "Somalia"],
    .l_ab: ["Abkhazia", "Georgia", "Russia"],
    .l_ae: ["Afghanistan", "Iran"],
    .l_af: ["Namibia", "South Africa"],
    .l_ak: ["Ghana"],
    .l_am: ["Ethiopia"],
    .l_an: ["Spain"],
    .l_ar: ["Algeria", "Bahrain", "Comoros", "Djibouti", "Egypt", "Iraq", "Israel", "Jordan", "Kuwait", "Lebanon", "Libya", "Mauritania", "Morocco", "Oman", "Palestine", "Qatar", "Saudi Arabia", "Somalia", "Sudan", "Syria", "Tunisia", "United Arab Emirates", "Yemen"],
    .l_as: ["India"],
    .l_av: ["Russia"],
    .l_ay: ["Bolivia", "Peru"],
    .l_az: ["Azerbaijan", "Iran", "Iraq", "Russia", "Turkey"],
    .l_ba: ["Russia"],
    .l_be: ["Belarus"],
    .l_bg: ["Bulgaria"],
    .l_bh: ["India"],
    .l_bi: ["Burundi"],
    .l_bm: ["Mali"],
    .l_bn: ["Bangladesh", "India"],
    .l_bo: ["China", "India"],
    .l_br: ["France"],
    .l_bs: ["Bosnia and Herzegovina"],
    .l_ca: ["Andorra", "France", "Italy", "Spain"],
    .l_ce: ["Russia"],
    .l_ch: ["United States"],
    .l_co: ["France"],
    .l_cr: ["Canada"],
    .l_cs: ["Czech Republic"],
    .l_cu: ["Bulgaria", "Russia", "Ukraine"],
    .l_cv: ["Russia"],
    .l_cy: ["United Kingdom"],
    .l_da: ["Denmark"],
    .l_de: ["Austria", "Belgium", "Germany", "Liechtenstein", "Luxembourg", "Switzerland"],
    .l_dv: ["Maldives"],
    .l_dz: ["Bhutan"],
    .l_ee: ["Ghana", "Togo"],
    .l_el: ["Cyprus", "Greece"],
    .l_en: ["Australia", "Belize", "Canada", "Ireland", "Jamaica", "New Zealand", "United Kingdom", "United States"],
    .l_eo: ["International"],
    .l_es: ["Argentina", "Bolivia", "Chile", "Colombia", "Costa Rica", "Cuba", "Dominican Republic", "Ecuador", "El Salvador", "Equatorial Guinea", "Guatemala", "Honduras", "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru", "Puerto Rico", "Spain", "Uruguay", "Venezuela"],
    .l_et: ["Estonia"],
    .l_eu: ["France", "Spain"],
    .l_fa: ["Afghanistan", "Iran"],
    .l_ff: ["Gambia", "Senegal"],
    .l_fi: ["Finland"],
    .l_fj: ["Fiji"],
    .l_fo: ["Faroe Islands", "Denmark"],
    .l_fr: ["France", "French Guiana", "Guadeloupe", "Martinique", "Réunion", "Mayotte", "Saint Pierre and Miquelon", "Wallis and Futuna", "New Caledonia"],
    .l_fy: ["Frisian"],
    .l_ga: ["Ireland"],
    .l_gd: ["Scotland"],
    .l_gl: ["Greenland", "Denmark"],
    .l_gn: ["Guinea"],
    .l_gu: ["Guam"],
    .l_gv: ["Guernsey"],
    .l_ha: ["Hausa"],
    .l_he: ["Hebrew", "Israel"],
    .l_hi: ["Hindi", "India"],
    .l_ho: ["Hiri Motu", "Papua New Guinea"],
    .l_hr: ["Croatian", "Bosnia and Herzegovina", "Croatia"],
    .l_ht: ["Haitian Creole", "Haiti"],
    .l_hu: ["Hungarian", "Hungary", "Slovakia", "Ukraine"],
    .l_hy: ["Armenian", "Armenia"],
    .l_hz: ["Herero", "Namibia"],
    .l_ia: ["Interlingua"],
    .l_id: ["Indonesian", "Indonesia"],
    .l_ie: ["Interlingue"],
    .l_ig: ["Igbo", "Nigeria"],
    .l_ii: ["Sichuan Yi", "China"],
    .l_ik: ["Inupiaq", "United States"],
    .l_io: ["Ido"],
    .l_is: ["Icelandic", "Iceland"],
    .l_it: ["Italian", "Italy", "Switzerland", "Vatican City"],
    .l_iu: ["Inuktitut", "Canada"],
    .l_ja: ["Japanese", "Japan"],
    .l_jv: ["Javanese", "Indonesia"],
    .l_ka: ["Georgian", "Georgia"],
    .l_kg: ["Kongo", "Democratic Republic of the Congo"],
    .l_ki: ["Kikuyu, Gikuyu", "Kenya"],
    .l_kj: ["Kwanyama, Kuanyama", "Angola"],
    .l_kk: ["Kazakh", "Kazakhstan"],
    .l_kl: ["Kalaallisut, Greenlandic", "Greenland, Denmark"],
    .l_km: ["Central Khmer", "Cambodia"],
    .l_kn: ["Kannada", "India"],
    .l_ko: ["Korean", "North Korea", "South Korea"],
    .l_kr: ["Kanuri", "Nigeria"],
    .l_ks: ["Kashmiri", "India"],
    .l_ku: ["Kurdish", "Iraq", "Iran", "Turkey"],
    .l_kv: ["Komi", "Russian Federation"],
    .l_kw: ["Cornish", "United Kingdom"],
    .l_ky: ["Kirghiz, Kyrgyz", "Kyrgyzstan"],
    .l_la: ["Latin"],
    .l_lb: ["Luxembourgish, Letzeburgesch", "Luxembourg", "Belgium"],
    .l_lg: ["Ganda", "Uganda"],
    .l_li: ["Limburgan, Limburger, Limburgish", "Belgium", "Netherlands"],
    .l_ln: ["Lingala", "Democratic Republic of the Congo", "Central African Republic", "Congo"],
    .l_lo: ["Lao", "Laos"],
    .l_lt: ["Lithuanian", "Lithuania"],
    .l_lu: ["Luxembourgish", "Lëtzebuergesch"],
    .l_lv: ["Latvian", "Latviešu valoda"],
    .l_mg: ["Malagasy", "Malagasy fiteny"],
    .l_mh: ["Marshallese", "Kajin M̧ajeļ"],
    .l_mi: ["Maori", "Te Reo Māori"],
    .l_mk: ["Macedonian", "македонски јазик"],
    .l_ml: ["Malian", "ߒߞߏ"],
    .l_mn: ["Mongolian", "Монгол хэл"],
    .l_mr: ["Marathi", "मराठी"],
    .l_ms: ["Malay", "Bahasa Melayu, بهاس ملايو‎"],
    .l_mt: ["Maltese", "Malti"],
    .l_my: ["Burmese", "ဗမာစာ"],
    .l_na: ["Nauru", "Ekakairũ Naoero"],
    .l_nb: ["Norwegian Bokmål", "Norsk bokmål"],
    .l_nd: ["North Ndebele", "IsiNdebele"],
    .l_ne: ["Nepali", "नेपाली"],
    .l_ng: ["Ndonga", "Owambo"],
    .l_nl: ["Dutch", "Nederlands, Vlaams"],
    .l_nn: ["Norwegian Nynorsk", "Norsk nynorsk"],
    .l_no: ["Norwegian", "Norsk"],
    .l_nr: ["South Ndebele", "IsiNdebele"],
    .l_nv: ["Navajo", "Diné bizaad"],
    .l_ny: ["Chichewa", "ChiCheŵa, chinyanja"],
    .l_oc: ["Occitan", "occitan, lenga d'òc"],
    .l_oj: ["Ojibwe", "ᐊᓂᔑᓈᐯᒧᐎᓐ"],
    .l_om: ["Oromo", "Afaan Oromoo"],
    .l_or: ["Oriya", "ଓଡ଼ିଆ"],
    .l_os: ["Ossetian", "ирон æвзаг"],
    .l_pa: ["Punjabi", "ਪੰਜਾਬੀ, پنجابی‎"],
    .l_pi: ["Pali", "पालि, पाळि"],
    .l_pl: ["Polish", "Polski"],
    .l_ps: ["Pashto", "پښتو"],
    .l_pt: ["Portuguese", "Português"],
    .l_qu: ["Quechua", "Runa Simi, Kichwa"],
    .l_rm: ["Romansh", "rumantsch grischun"],
    .l_rn: ["Kirundi", "Ikirundi"],
    .l_ro: ["Romanian", "Română"],
    .l_ru: ["Russian", "русский"],
    .l_rw: ["Kinyarwanda", "Ikinyarwanda"],
    .l_sa: ["Sanskrit", "संस्कृतम्"],
    .l_sc: ["Sardinian", "sardu"],
    .l_sd: ["Sindhi", "सिन्धी, سنڌي، سندھی‎"],
    .l_se: ["Northern Sami", "Davvisámegiella"],
    .l_sg: ["Sango", "Yângâ tî sängö"],
    .l_si: ["Sinhalese", "සිංහල"],
    .l_sk: ["Slovak", "slovenčina, slovenský jazyk"],
    .l_sl: ["Slovenian", "slovenski jezik, slovenščina"],
    .l_sm: ["Samoan", "gagana fa'a Samoa"],
    .l_sn: ["Shona", "chiShona"],
    .l_so: ["Somali", "Soomaaliga, af Soomaali"],
    .l_sq: ["Albanian", "Shqip"],
    .l_sr: ["Serbian", "српски језик"],
    .l_ss: ["Swati", "SiSwati"],
    .l_st: ["Southern Sotho", "Sesotho"],
    .l_su: ["Sundanese", "Basa Sunda"],
    .l_sv: ["Swedish", "svenska"],
    .l_sw: ["Swahili", "Kiswahili"],
    .l_ta: ["Tamil", "தமிழ்"],
    .l_te: ["Telugu", "తెలుగు"],
    .l_tg: ["Tajik", "тоҷикӣ, toğikī, تاجیکی‎"],
    .l_th: ["Thai", "ไทย"],
    .l_ti: ["Tigrinya", "ትግርኛ"],
    .l_tk: ["Turkmen", "Türkmen, Түркмен"],
    .l_tl: ["Tagalog", "Wikang Tagalog"],
    .l_tn: ["Tswana", "Setswana"],
    .l_to: ["Tonga (Tonga Islands)", "faka Tonga"],
    .l_tr: ["Turkish", "Türkçe"],
    .l_ts: ["Tsonga", "Xitsonga"],
    .l_tt: ["Tatar", "татар теле, tatar tele"],
    .l_tw: ["Twi", "Twi"],
    .l_ty: ["Tahitian", "Reo Tahiti"],
    .l_ug: ["Uighur", "ئۇيغۇرچە‎, Uyghurche"],
    .l_uk: ["Ukrainian", "українська"],
    .l_ur: ["Urdu", "اردو"],
    .l_uz: ["Uzbek", "Oʻzbek, Ўзбек, أۇزبېك‎"],
    .l_ve: ["Venda", "Tshivenḓa"],
    .l_vi: ["Vietnamese", "Tiếng Việt"],
    .l_vo: ["Volapük", "Volapük"],
    .l_wa: ["Walloon", "Walon"],
    .l_wo: ["Wolof", "Wollof"],
    .l_xh: ["Xhosa", "isiXhosa"],
    .l_yi: ["Yiddish", "ייִדיש"],
    .l_yo: ["Yoruba", "Yorùbá"],
    .l_za: ["Zhuang, Chuang", "Saɯ cueŋƅ, Saw cuengh"]
]
    
enum LanguageCode: String {
    
    case l_aa = "Afar"
    case l_ab = "Abkhazian"
    case l_ae = "Avestan"
    case l_af = "Afrikaans"
    case l_ak = "Akan"
    case l_am = "Amharic"
    case l_an = "Aragonese"
    case l_ar = "Arabic"
    case l_as = "Assamese"
    case l_av = "Avaric"
    case l_ay = "Aymara"
    case l_az = "Azerbaijani"
    case l_ba = "Bashkir"
    case l_be = "Belarusian"
    case l_bg = "Bulgarian"
    case l_bh = "Bihari"
    case l_bi = "Bislama"
    case l_bm = "Bambara"
    case l_bn = "Bengali"
    case l_bo = "Tibetan"
    case l_br = "Breton"
    case l_bs = "Bosnian"
    case l_ca = "Catalan"
    case l_ce = "Chechen"
    case l_ch = "Chamorro"
    case l_co = "Corsican"
    case l_cr = "Cree"
    case l_cs = "Czech"
    case l_cu = "Church Slavic"
    case l_cv = "Chuvash"
    case l_cy = "Welsh"
    case l_da = "Danish"
    case l_de = "German"
    case l_dv = "Divehi"
    case l_dz = "Dzongkha"
    case l_ee = "Ewe"
    case l_el = "Greek"
    case l_en = "English"
    case l_eo = "Esperanto"
    case l_es = "Spanish"
    case l_et = "Estonian"
    case l_eu = "Basque"
    case l_fa = "Persian"
    case l_ff = "Fulah"
    case l_fi = "Finnish"
    case l_fj = "Fijian"
    case l_fo = "Faroese"
    case l_fr = "French"
    case l_fy = "Western Frisian"
    case l_ga = "Irish"
    case l_gd = "Scottish Gaelic"
    case l_gl = "Galician"
    case l_gn = "Guarani"
    case l_gu = "Gujarati"
    case l_gv = "Manx"
    case l_ha = "Hausa"
    case l_he = "Hebrew"
    case l_hi = "Hindi"
    case l_ho = "Hiri Motu"
    case l_hr = "Croatian"
    case l_ht = "Haitian"
    case l_hu = "Hungarian"
    case l_hy = "Armenian"
    case l_hz = "Herero"
    case l_ia = "Interlingua"
    case l_id = "Indonesian"
    case l_ie = "Interlingue"
    case l_ig = "Igbo"
    case l_ii = "Sichuan Yi"
    case l_ik = "Inupiaq"
    case l_io = "Ido"
    case l_is = "Icelandic"
    case l_it = "Italian"
    case l_iu = "Inuktitut"
    case l_ja = "Japanese"
    case l_jv = "Javanese"
    case l_ka = "Georgian"
    case l_kg = "Kongo"
    case l_ki = "Kikuyu"
    case l_kj = "Kuanyama"
    case l_kk = "Kazakh"
    case l_kl = "Kalaallisut"
    case l_km = "Central Khmer"
    case l_kn = "Kannada"
    case l_ko = "Korean"
    case l_kr = "Kanuri"
    case l_ks = "Kashmiri"
    case l_ku = "Kurdish"
    case l_kv = "Komi"
    case l_kw = "Cornish"
    case l_ky = "Kirghiz"
    case l_la = "Latin"
    case l_lb = "Luxembourgish"
    case l_lg = "Ganda"
    case l_li = "Limburgan"
    case l_ln = "Lingala"
    case l_lo = "Lao"
    case l_lt = "Lithuanian"
    case l_lu = "Luba-Katanga"
    case l_lv = "Latvian"
    case l_mg = "Malagasy"
    case l_mh = "Marshallese"
    case l_mi = "Maori"
    case l_mk = "Macedonian"
    case l_ml = "Malayalam"
    case l_mn = "Mongolian"
    case l_mr = "Marathi"
    case l_ms = "Malay"
    case l_mt = "Maltese"
    case l_my = "Burmese"
    case l_na = "Nauru"
    case l_nb = "Norwegian Bokmål"
    case l_nd = "North Ndebele"
    case l_ne = "Nepali"
    case l_ng = "Ndonga"
    case l_nl = "Dutch"
    case l_nn = "Norwegian Nynorsk"
    case l_no = "Norwegian"
    case l_nr = "South Ndebele"
    case l_nv = "Navajo"
    case l_ny = "Chichewa"
    case l_oc = "Occitan"
    case l_oj = "Ojibwa"
    case l_om = "Oromo"
    case l_or = "Oriya"
    case l_os = "Ossetian"
    case l_pa = "Panjabi"
    case l_pi = "Pali"
    case l_pl = "Polish"
    case l_ps = "Pashto"
    case l_pt = "Portuguese"
    case l_qu = "Quechua"
    case l_rm = "Raeto-Romance"
    case l_rn = "Kirundi"
    case l_ro = "Romanian"
    case l_ru = "Russian"
    case l_rw = "Kinyarwanda"
    case l_sa = "Sanskrit"
    case l_sc = "Sardinian"
    case l_sd = "Sindhi"
    case l_se = "Northern Sami"
    case l_sg = "Sango"
    case l_si = "Sinhala"
    case l_sk = "Slovak"
    case l_sl = "Slovenian"
    case l_sm = "Samoan"
    case l_sn = "Shona"
    case l_so = "Somali"
    case l_sq = "Albanian"
    case l_sr = "Serbian"
    case l_ss = "Swati"
    case l_st = "Southern Sotho"
    case l_su = "Sundanese"
    case l_sv = "Swedish"
    case l_sw = "Swahili"
    case l_ta = "Tamil"
    case l_te = "Telugu"
    case l_tg = "Tajik"
    case l_th = "Thai"
    case l_ti = "Tigrinya"
    case l_tk = "Turkmen"
    case l_tl = "Tagalog"
    case l_tn = "Tswana"
    case l_to = "Tonga"
    case l_tr = "Turkish"
    case l_ts = "Tsonga"
    case l_tt = "Tatar"
    case l_tw = "Twi"
    case l_ty = "Tahitian"
    case l_ug = "Uighur"
    case l_uk = "Ukrainian"
    case l_ur = "Urdu"
    case l_uz = "Uzbek"
    case l_ve = "Venda"
    case l_vi = "Vietnamese"
    case l_vo = "Volapük"
    case l_wa = "Walloon"
    case l_wo = "Wolof"
    case l_xh = "Xhosa"
    case l_yi = "Yiddish"
    case l_yo = "Yoruba"
    case l_za = "Zhuang"
    case l_zh = "Chinese"
    case l_zu = "Zulu"
    
    static let allCodes: [LanguageCode] = [.l_aa, .l_ab, .l_ae, .l_af, .l_ak, .l_am, .l_an, .l_ar, .l_as, .l_av, .l_ay, .l_az, .l_ba, .l_be, .l_bg, .l_bh, .l_bi, .l_bm, .l_bn, .l_bo, .l_br, .l_bs, .l_ca, .l_ce, .l_ch, .l_co, .l_cr, .l_cs, .l_cu, .l_cv, .l_cy, .l_da, .l_de, .l_dv, .l_dz, .l_ee, .l_el, .l_en, .l_eo, .l_es, .l_et, .l_eu, .l_fa, .l_ff, .l_fi, .l_fj, .l_fo, .l_fr, .l_fy, .l_ga, .l_gd, .l_gl, .l_gn, .l_gu, .l_gv, .l_ha, .l_he, .l_hi, .l_ho, .l_hr, .l_ht, .l_hu, .l_hy, .l_hz, .l_ia, .l_id, .l_ie, .l_ig, .l_ii, .l_ik, .l_io, .l_is, .l_it, .l_iu, .l_ja, .l_jv, .l_ka, .l_kg, .l_ki, .l_kj, .l_kk, .l_kl, .l_km, .l_kn, .l_ko, .l_kr, .l_ks, .l_ku, .l_kv, .l_kw, .l_ky, .l_la, .l_lb, .l_lg, .l_li, .l_ln, .l_lo, .l_lt, .l_lu, .l_lv, .l_mg, .l_mh, .l_mi, .l_mk, .l_ml, .l_mn, .l_mr, .l_ms, .l_mt, .l_my, .l_na, .l_nb, .l_nd, .l_ne, .l_ng, .l_nl, .l_nn, .l_no, .l_nr, .l_nv, .l_ny, .l_oc, .l_oj, .l_om, .l_or, .l_os, .l_pa, .l_pi, .l_pl, .l_ps, .l_pt, .l_qu, .l_rm, .l_rn, .l_ro, .l_ru, .l_rw, .l_sa, .l_sc, .l_sd, .l_se, .l_sg,  .l_si, .l_sk, .l_sl, .l_sm, .l_sn, .l_so, .l_sq, .l_sr, .l_ss, .l_st, .l_su, .l_sv, .l_sw, .l_ta, .l_te, .l_tg, .l_th, .l_ti, .l_tk, .l_tl, .l_tn, .l_to, .l_tr, .l_ts, .l_tt, .l_tw, .l_ty, .l_ug, .l_uk, .l_ur, .l_uz, .l_ve, .l_vi, .l_vo, .l_wa, .l_wo, .l_xh, .l_yi, .l_yo, .l_za, .l_zh, .l_zu]
    /*
     
     
     The line static let allCodes: [LanguageCode] = [.l_aa, .l_ab, .l_ae, .l_af, .l_ak, .l_am, ...] is defining a static property of the LanguageCode enum that is an array containing all the cases of the LanguageCode enum.

     This allows you to access a list of all the language codes in the enum without having to hard-code them every time you need to use them, as you can simply reference the static allCodes property.

     For example, if you wanted to iterate over all the language codes in the LanguageCode enum, you could do something like this:

     Yes, static let allCodes can be useful for various purposes such as:

     Populating a picker view or a table view with all the available options for the user to select from.
     Validating user input to ensure that it is one of the available options.
     Filtering or searching a collection of objects based on a specific property or attribute.
     Generating reports or statistics based on the frequency or distribution of certain values or categories.
     Basically, it provides a convenient way to access all the cases of the enum as an array, which can be useful in many different contexts.
     
     
     for code in LanguageCode.allCodes {
         print(code.rawValue)
     }
     
     
     */
}

let languageNamesInLocaleLanguage: [String : String] = [
    "aa": "Afaraf",
    "ab": "Аҧсуа бызшәа, аҧсшәа",
    "ae": "avesta",
    "af": "Afrikaans",
    "ak": "Akan",
    "am": "አማርኛ",
    "an": "aragonés",
    "ar": "العربية",
    "as": "অসমীয়া",
    "av": "авар мацӀ, магӀарул мацӀ",
    "ay": "aymar aru",
    "az": "azərbaycan dili",
    "ba": "башҡорт теле",
    "be": "беларуская мова",
    "bg": "български език",
    "bh": "भोजपुरी",
    "bi": "Bislama",
    "bm": "bamanankan",
    "bn": "বাংলা",
    "bo": "བོད་ཡིག",
    "br": "brezhoneg",
    "bs": "bosanski jezik",
    "ca": "català",
    "ce": "нохчийн мотт",
    "ch": "Chamoru",
    "co": "corsu, lingua corsa",
    "cr": "ᓀᐦᐃᔭᐍᐏᐣ",
    "cs": "čeština, český jazyk",
    "cu": "ѩзыкъ словѣньскъ",
    "cv": "чӑваш чӗлхи",
    "cy": "Cymraeg",
    "da": "dansk",
    "de": "Deutsch",
    "dv": "ދިވެހި",
    "dz": "རྫོང་ཁ",
    "ee": "Eʋegbe",
    "el": "ελληνικά",
    "en": "English",
    "eo": "Esperanto",
    "es": "español, castellano",
    "et": "eesti, eesti keel",
    "eu": "euskara, euskera",
    "fa": "فارسی",
    "ff": "Fulfulde, Pulaar, Pular",
    "fi": "suomi, suomen kieli",
    "fj": "vosa Vakaviti",
    "fo": "føroyskt",
    "fr": "français, langue française",
    "fy": "Frysk",
    "ga": "Gaeilge",
    "gd": "Gàidhlig",
    "gl": "galego",
    "gn": "Avañe'ẽ",
    "gu": "ગુજરાતી",
    "gv": "Gaelg, Gailck",
    "ha": "Hausa, هَوُسَ",
    "he": "עברית",
    "hi": "हिन्दी, हिंदी",
    "ho": "Hiri Motu",
    "hr": "hrvatski jezik",
    "ht": "Kreyòl ayisyen",
    "hu": "magyar",
    "hy": "Հայերեն",
    "hz": "Otjiherero",
    "ia": "interlingua",
    "id": "Bahasa Indonesia",
    "ie": "Interlingue",
    "ig": "Igbo",
    "ii": "ꆈꌠ꒿ Nuosuhxop",
    "ik": "Iñupiaq, Iñupiatun",
    "io": "Ido",
    "is": "íslenska",
    "it": "italiano",
    "iu": "ᐃᓄᒃᑎᑐᑦ",
    "ja": "日本語",
    "jv": "basa Jawa",
    "ka": "ქართული",
    "kg": "Kikongo",
    "ki": "Gĩkũyũ",
    "kj": "Kuanyama",
    "kk": "қазақ тілі",
    "kl": "kalaallisut, kalaallit oqaasii",
    "km": "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ",
    "kn": "ಕನ್ನಡ",
    "ko": "한국어",
    "kr": "Kanuri",
    "ks": "कश्मीरी, كشميري‎",
    "ku": "Kurdî, كوردی‎",
    "kv": "коми кыв",
    "kw": "Kernewek",
    "ky": "кыргыз тили",
    "la": "latine, lingua latina",
    "lb": "Lëtzebuergesch",
    "lg": "Luganda",
    "li": "Limburgs",
    "ln": "Lingála",
    "lo": "ພາສາລາວ",
    "lt": "lietuvių kalba",
    "lu": "Tshiluba",
    "lv": "latviešu valoda",
    "mg": "Malagasy fiteny",
    "mh": "Kajin M̧ajeļ",
    "mi": "te reo Māori",
    "mk": "македонски јазик",
    "ml": "മലയാളം",
    "mn": "монгол",
    "mr": "मराठी",
    "ms": "Bahasa Melayu, بهاس ملايو‎",
    "mt": "Malti",
    "my": "ဗမာစာ",
    "na": "Ekakairũ Naoero",
    "nb": "norsk bokmål",
    "nd": "isiNdebele",
    "ne": "नेपाली",
    "ng": "Owambo",
    "nl": "Nederlands, Vlaams",
    "nn": "norsk nynorsk",
    "no": "norsk",
    "nr": "isiNdebele",
    "nv": "Diné bizaad, Dinékʼehǰí",
    "ny": "chiCheŵa, chinyanja",
    "oc": "occitan, lenga d'òc",
    "oj": "ᐊᓂᔑᓈᐯᒧᐎᓐ",
    "om": "Afaan Oromoo",
    "or": "ଓଡ଼ିଆ",
    "os": "ирон æвзаг",
    "pa": "ਪੰਜਾਬੀ, پنجابی‎",
    "pi": "पाऴि",
    "pl": "polski",
    "ps": "پښتو",
    "pt": "português",
    "qu": "Runa Simi, Kichwa",
    "rm": "rumantsch grischun",
    "rn": "Ikirundi",
    "ro": "română",
    "ru": "русский язык",
    "rw": "Ikinyarwanda",
    "sa": "संस्कृतम्",
    "sc": "sardu",
    "sd": "सिन्धी, سنڌي، سندھی‎",
    "se": "Davvisámegiella",
    "sg": "yângâ tî sängö",
    "sh": "srpskohrvatski / српскохрватски",
    "si": "සිංහල",
    "sk": "slovenčina",
    "sl": "slovenščina",
    "sm": "gagana fa'a Samoa",
    "sn": "chiShona",
    "so": "Soomaaliga, af Soomaali",
    "sq": "shqip",
    "sr": "српски језик",
    "ss": "SiSwati",
    "st": "Sesotho",
    "su": "Basa Sunda",
    "sv": "svenska",
    "sw": "Kiswahili",
    "ta": "தமிழ்",
    "te": "తెలుగు",
    "tg": "тоҷикӣ, toğikī, تاجیکی‎",
    "th": "ไทย",
    "ti": "ትግርኛ",
    "tk": "Türkmen, Түркмен",
    "tl": "Tagalog",
    "tn": "Setswana",
    "to": "faka Tonga",
    "tr": "Türkçe",
    "ts": "XiTsonga",
    "tt": "татар теле, tatar tele",
    "tw": "Twi",
    "ty": "Reo Tahiti",
    "ug": "Uyƣurqə, ئۇيغۇرچە‎",
    "uk": "українська мова",
    "ur": "اردو",
    "uz": "oʻzbek, Ўзбек, أۇزبېك‎",
    "ve": "Tshivenḓa",
    "vi": "Tiếng Việt",
    "vo": "Volapük",
    "wa": "Walon",
    "wo": "Wollof",
    "xh": "isiXhosa",
    "yi": "ייִדיש",
    "yo": "Yorùbá",
    "za": "Saɯ cueŋƅ, Saw cuengh",
    "zh": "中文 (Zhōngwén), 汉语, 漢語",
    "zu": "isiZulu"

]



let languagesArray: [[String]] = [
    ["aa", "Afar", "Afaraf"],
    ["ab", "Abkhazian", "Аҧсуа бызшәа, аҧсшәа"],
    ["ae", "Avestan", "avesta"],
    ["af", "Afrikaans", "Afrikaans"],
    ["ak", "Akan", "Akan"],
    ["am", "Amharic", "አማርኛ"],
    ["an", "Aragonese", "aragonés"],
    ["ar", "Arabic", "العربية"],
    ["as", "Assamese", "অসমীয়া"],
    ["av", "Avaric", "авар мацӀ, магӀарул мацӀ"],
    ["ay", "Aymara", "aymar aru"],
    ["az", "Azerbaijani", "azərbaycan dili"],
    ["ba", "Bashkir", "башҡорт теле"],
    ["be", "Belarusian", "беларуская мова"],
    ["bg", "Bulgarian", "български език"],
    ["bh", "Bihari", "भोजपुरी"],
    ["bi", "Bislama", "Bislama"],
    ["bm", "Bambara", "bamanankan"],
    ["bn", "Bengali", "বাংলা"],
    ["bo", "Tibetan", "བོད་ཡིག"],
    ["br", "Breton", "brezhoneg"],
    ["bs", "Bosnian", "bosanski jezik"],
    ["ca", "Catalan", "català"],
    ["ce", "Chechen", "нохчийн мотт"],
    ["ch", "Chamorro", "Chamoru"],
    ["co", "Corsican", "corsu, lingua corsa"],
    ["cr", "Cree", "ᓀᐦᐃᔭᐍᐏᐣ"],
    ["cs", "Czech", "čeština, český jazyk"],
    ["cu", "Old Church Slavonic", "ѩзыкъ словѣньскъ"],
    ["cv", "Chuvash", "чӑваш чӗлхи"],
    ["cy", "Welsh", "Cymraeg"],
    ["da", "Danish", "dansk"],
    ["de", "German", "Deutsch"],
    ["dv", "Divehi", "ދިވެހި"],
    ["dz", "Dzongkha", "རྫོང་ཁ"],
    ["ee", "Ewe", "Eʋegbe"],
    ["el", "Greek", "Ελληνικά"],
    ["en", "English"],
    ["eo", "Esperanto", "Esperanto"],
    ["es", "Spanish", "español, castellano"],
    ["et", "Estonian", "eesti, eesti keel"],
    ["eu", "Basque", "euskara, euskera"],
    ["fa", "Persian", "فارسی"],
    ["ff", "Fulah", "Fulfulde, Pulaar, Pular"],
    ["fi", "Finnish", "suomi, suomen kieli"],
    ["fj", "Fijian", "vosa Vakaviti"],
    ["fo", "Faroese", "føroyskt"],
    ["fr", "French", "français, langue française"],
    ["fy", "Western Frisian", "Frysk"],
    ["ga", "Irish", "Gaeilge"],
    ["gd", "Scottish Gaelic", "Gàidhlig"],
    ["gl", "Galician", "galego"],
    ["gn", "Guarani", "Avañe'ẽ"],
    ["gu", "Gujarati", "ગુજરાતી"],
    ["gv", "Manx", "Gaelg, Gailck"],
    ["ha", "Hausa", "Hausa, هَوُسَ"],
    ["he", "Hebrew", "עברית"],
    ["hi", "Hindi", "हिन्दी, हिंदी"],
    ["ho", "Hiri Motu", "Hiri Motu"],
    ["hr", "Croatian", "hrvatski"],
    ["ht", "Haitian", "Kreyòl ayisyen"],
    ["hu", "Hungarian", "magyar"],
    ["hy", "Armenian", "Հայերեն"],
    ["hz", "Herero", "Otjiherero"],
    ["ia", "Interlingua", "Interlingua"],
    ["id", "Indonesian", "Bahasa Indonesia"],
    ["ie", "Interlingue", "Interlingue"],
    ["ig", "Igbo", "Asụsụ Igbo"],
    ["ii", "Sichuan Yi", "ꆇꉙ"],
    ["ik", "Inupiaq", "Iñupiaq, Iñupiatun"],
    ["io", "Ido", "Ido"],
    ["is", "Icelandic", "íslenska"],
    ["it", "Italian", "italiano"],
    ["iu", "Inuktitut", "ᐃᓄᒃᑎᑐᑦ"],
    ["ja", "Japanese", "日本語"],
    ["jv", "Javanese", "basa Jawa"],
    ["ka", "Georgian", "ქართული"],
    ["kg", "Kongo", "KiKongo"],
    ["ki", "Kikuyu", "Gĩkũyũ"],
    ["kj", "Kuanyama", "Kuanyama"],
    ["kk", "Kazakh", "қазақ тілі"],
    ["kl", "Kalaallisut", "kalaallisut, kalaallit oqaasii"],
    ["km", "Khmer", "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ"],
    ["kn", "Kannada", "ಕನ್ನಡ"],
    ["ko", "Korean", "한국어 (韓國語), 조선말 (朝鮮語)"],
    ["kr", "Kanuri", "Kanuri"],
    ["ks", "Kashmiri", "कश्मीरी, كشميري‎"],
    ["ku", "Kurdish", "Kurdî, كوردی‎"],
    ["kv", "Komi", "коми кыв"],
    ["kw", "Cornish", "Kernewek"],
    ["ky", "Kirghiz", "кыргыз тили"],
    ["la", "Latin", "latine, lingua latina"],
    ["lb", "Luxembourgish", "Lëtzebuergesch"],
    ["lg", "Ganda", "Luganda"],
    ["li", "Limburgish", "Limburgs"],
    ["ln", "Lingala", "Lingála"],
    ["lo", "Lao", "ພາສາລາວ"],
    ["lt", "Lithuanian", "lietuvių kalba"],
    ["lu", "Luba-Katanga", "Tshiluba"],
    ["lv", "Latvian", "latviešu valoda"],
    ["mg", "Malagasy", "fiteny malagasy"],
    ["mh", "Marshallese", "Kajin M̧ajeļ"],
    ["mi", "Maori", "te reo Māori"],
    ["mk", "Macedonian", "македонски јазик"],
    ["ml", "Malayalam", "മലയാളം"],
    ["mn", "Mongolian", "Монгол хэл"],
    ["mr", "Marathi", "मराठी"],
    ["ms", "Malay", "bahasa Melayu, بهاس ملايو‎"],
    ["mt", "Maltese", "Malti"],
    ["my", "Burmese", "ဗမာစာ"],
    ["na", "Nauru", "Ekakairũ Naoero"],
    ["nb", "Norwegian Bokmål", "Norsk bokmål"],
    ["nd", "North Ndebele", "isiNdebele"],
    ["ne", "Nepali", "नेपाली"],
    ["ng", "Ndonga", "Owambo"],
    ["nl", "Dutch", "Nederlands, Vlaams"],
    ["nn", "Norwegian Nynorsk", "Norsk nynorsk"],
    ["no", "Norwegian", "Norsk"],
    ["nr", "South Ndebele", "isiNdebele"],
    ["nv", "Navajo", "Diné bizaad, Dinékʼehǰí"],
    ["ny", "Chichewa", "chiCheŵa, chinyanja"],
    ["oc", "Occitan", "occitan, lenga d'òc"],
    ["oj", "Ojibwa", "ᐊᓂᔑᓈᐯᒧᐎᓐ"],
    ["om", "Oromo", "Afaan Oromoo"],
    ["or", "Oriya", "ଓଡ଼ିଆ"],
    ["os", "Ossetian", "ирон æвзаг"],
    ["pa", "Panjabi", "ਪੰਜਾਬੀ, پنجابی‎"],
    ["pi", "Pali", "पाऴि"],
    ["pl", "Polish", "polski"],
    ["ps", "Pashto", "پښتو"],
    ["pt", "Portuguese", "Português"],
    ["qu", "Quechua", "Runa Simi, Kichwa"],
    ["rm", "Romansh", "rumantsch grischun"],
    ["rn", "Kirundi", "kiRundi"],
    ["ro", "Romanian", "română"],
    ["ru", "Russian", "русский язык"],
    ["rw", "Kinyarwanda", "Ikinyarwanda"],
    ["sa", "Sanskrit", "संस्कृतम्"],
    ["sc", "Sardinian", "sardu"],
    ["sd", "Sindhi", "सिन्धी, سنڌي، سندھی‎"],
    ["se", "Northern Sami", "Davvisámegiella"],
    ["sg", "Sango", "yângâ tî sängö"],
    ["si", "Sinhala", "සිංහල"],
    ["sk", "Slovak", "slovenčina"],
    ["sl", "Slovenian", "slovenščina"],
    ["sm", "Samoan", "gagana fa'a Samoa"],
    ["sn", "Shona", "chiShona"],
    ["so", "Somali", "Soomaaliga, af Soomaali"],
    ["sq", "Albanian", "Shqip"],
    ["sr", "Serbian", "српски језик"],
    ["ss", "Swati", "SiSwati"],
    ["st", "Southern Sotho", "Sesotho"],
    ["su", "Sundanese", "Basa Sunda"],
    ["sv", "Swedish", "svenska"],
    ["sw", "Swahili", "Kiswahili"],
    ["ta", "Tamil", "தமிழ்"],
    ["te", "Telugu", "తెలుగు"],
    ["tg", "Tajik", "тоҷикӣ, toğikī, تاجیکی‎"],
    ["th", "Thai", "ไทย"],
    ["ti", "Tigrinya", "ትግርኛ"],
    ["tk", "Turkmen", "Türkmen, Түркмен"],
    ["tl", "Tagalog", "Tagalog"],
    ["tn", "Tswana", "Setswana"],
    ["to", "Tonga", "faka Tonga"],
    ["tr", "Turkish", "Türkçe"],
    ["ts", "Tsonga", "Xitsonga"],
    ["tt", "Tatar", "татар теле, tatar tele"],
    ["tw", "Twi", "Twi"],
    ["ty", "Tahitian", "Reo Mā`ohi"],
    ["ug", "Uighur", "Uyƣurqə, ئۇيغۇرچە‎"],
    ["uk", "Ukrainian", "українська мова"],
    ["ur", "Urdu", "اردو"],
    ["uz", "Uzbek", "Oʻzbek, Ўзбек, أۇزبېك‎"],
    ["ve", "Venda", "Tshivenḓa"],
    ["vi", "Vietnamese", "Tiếng Việt"],
    ["vo", "Volapük", "Volapük"],
    ["wa", "Walloon", "Walon"],
    ["wo", "Wolof", "Wollof"],
    ["xh", "Xhosa", "isiXhosa"],
    ["yi", "Yiddish", "ייִדיש"],
    ["yo", "Yoruba", "Yorùbá"],
    ["za", "Zhuang", "Saɯ cueŋƅ, Saw cuengh"],
    ["zh", "Chinese", "中文 (Zhōngwén), 汉语, 漢語"],
    ["zu", "Zulu", "isiZulu"]
]


//let bloodGlucoseUnitsByCountries: [String: String] = [
//    "Afghanistan": "mg/dL",
//    "Albania": "mg/dL",
//    "Algeria": "mg/dL",
//    "Andorra": "mg/dL",
//    "Angola": "mg/dL",
//    "Antigua and Barbuda": "mg/dL",
//    "Argentina": "mg/dL",
//    "Armenia": "mg/dL",
//    "Australia": "mmol/L",
//    "Austria": "mmol/L",
//    "Azerbaijan": "mg/dL",
//    "Bahamas": "mg/dL",
//    "Bahrain": "mg/dL",
//    "Bangladesh": "mg/dL",
//    "Barbados": "mg/dL",
//    "Belarus": "mmol/L",
//    "Belgium": "mmol/L",
//    "Belize": "mg/dL",
//    "Benin": "mg/dL",
//    "Bhutan": "mg/dL",
//    "Bolivia": "mg/dL",
//    "Bosnia and Herzegovina": "mg/dL",
//    "Botswana": "mg/dL",
//    "Brazil": "mg/dL",
//    "Brunei": "mg/dL",
//    "Bulgaria": "mmol/L",
//    "Burkina Faso": "mg/dL",
//    "Burundi": "mg/dL",
//    "Cambodia": "mg/dL",
//    "Cameroon": "mg/dL",
//    "Canada": "mmol/L",
//    "Cape Verde": "mg/dL",
//    "Central African Republic": "mg/dL",
//    "Chad": "mg/dL",
//    "Chile": "mg/dL",
//    "China": "mg/dL",
//    "Colombia": "mg/dL",
//    "Comoros": "mg/dL",
//    "Congo": "mg/dL",
//    "Costa Rica": "mg/dL",
//    "Cote d'Ivoire": "mg/dL",
//    "Croatia": "mmol/L",
//    "Cuba": "mg/dL",
//    "Cyprus": "mg/dL",
//    "Czech Republic": "mmol/L",
//    "Denmark": "mmol/L",
//    "Djibouti": "mg/dL",
//    "Dominica": "mg/dL",
//    "Dominican Republic": "mg/dL",
//    "Ecuador": "mg/dL",
//    "Egypt": "mg/dL",
//    "El Salvador": "mg/dL",
//    "Equatorial Guinea": "mg/dL",
//    "Eritrea": "mg/dL",
//    "Estonia": "mmol/L",
//    "Ethiopia": "mg/dL",
//    "Fiji": "mmol/L",
//    "Finland": "mmol/L",
//    "France": "mmol/L",
//    "Gabon": "mg/dL",
//    "Gambia": "mg/dL",
//    "Georgia": "mg/dL",
//    "Germany": "mmol/L",
//    "Ghana": "mg/dL",
//    "Greece": "mmol/L",
//    "Grenada": "mg/dL",
//    "Guatemala": "mg/dL",
//    "Guinea": "mg/dL",
//    "Guinea-Bissau": "mg/dL",
//    "Guyana": "mg/dL",
//    "Haiti": "mg/dL",
//    "Honduras": "mg/dL",
//    "Hungary": "mmol/L",
//    "Iceland": "mmol/L",
//    "India": "mg/dL",
//    "Indonesia": "mg/dL",
//    "Iran": "mg/dL",
//    "Iraq": "mg/dL",
//    "Ireland": "mmol/L",
//    "Israel": "mmol/L",
//    "Italy": "mmol/L",
//    "Jamaica": "mg/dL",
//    "Japan": "mg/dL",
//    "Jordan": "mg/dL",
//    "Kazakhstan": "mg/dL",
//    "Kenya": "mg/dL",
//    "Kiribati": "mg/dL",
//    "North Korea": "mg/dL",
//    "South Korea": "mg/dL",
//    "Kosovo": "mg/dL",
//    "Kuwait": "mg/dL",
//    "Kyrgyzstan": "mg/dL",
//    "Laos": "mg/dL",
//    "Latvia": "mmol/L",
//    "Lebanon": "mg/dL",
//    "Lesotho": "mg/dL",
//    "Liberia": "mg/dL",
//    "Libya": "mg/dL",
//    "Liechtenstein": "mmol/L",
//    "Lithuania": "mmol/L",
//    "Luxembourg": "mmol/L",
//    "Macedonia": "mg/dL",
//    "Madagascar": "mg/dL",
//    "Malawi": "mg/dL",
//    "Malaysia": "mg/dL",
//    "Maldives": "mg/dL",
//    "Mali": "mg/dL",
//    "Malta": "mmol/L",
//    "Marshall Islands": "mg/dL",
//    "Mauritania": "mg/dL",
//    "Mauritius": "mg/dL",
//    "Mexico": "mg/dL",
//    "Micronesia": "mg/dL",
//    "Moldova": "mg/dL",
//    "Monaco": "mmol/L",
//    "Mongolia": "mg/dL",
//    "Montenegro": "mg/dL",
//    "Morocco": "mg/dL",
//    "Mozambique": "mg/dL",
//    "Myanmar": "mg/dL",
//    "Namibia": "mg/dL",
//    "Nauru": "mg/dL",
//    "Nepal": "mg/dL",
//    "Netherlands": "mmol/L",
//    "New Zealand": "mmol/L",
//    "Nicaragua": "mg/dL",
//    "Niger": "mg/dL",
//    "Nigeria": "mg/dL",
//    "Norway": "mmol/L",
//    "Oman": "mg/dL",
//    "Pakistan": "mg/dL",
//    "Palau": "mg/dL",
//    "Panama": "mg/dL",
//    "Papua New Guinea": "mg/dL",
//    "Paraguay": "mg/dL",
//    "Peru": "mg/dL",
//    "Philippines": "mg/dL",
//    "Poland": "mmol/L",
//    "Portugal": "mmol/L",
//    "Qatar": "mg/dL",
//    "Romania": "mg/dL",
//    "Russia": "mmol/L",
//    "Rwanda": "mg/dL",
//    "Saint Kitts and Nevis": "mg/dL",
//    "Saint Lucia": "mg/dL",
//    "Saint Vincent and the Grenadines": "mg/dL",
//    "Samoa": "mg/dL",
//    "San Marino": "mmol/L",
//    "Sao Tome and Principe": "mg/dL",
//    "Saudi Arabia": "mg/dL",
//    "Senegal": "mg/dL",
//    "Serbia": "mg/dL",
//    "Seychelles": "mg/dL",
//    "Sierra Leone": "mg/dL",
//    "Singapore": "mmol/L",
//    "Slovakia": "mmol/L",
//    "Slovenia": "mmol/L",
//    "Solomon Islands": "mg/dL",
//    "Somalia": "mg/dL",
//    "South Africa": "mg/dL",
//    "South Sudan": "mg/dL",
//    "Spain": "mmol/L",
//    "Sri Lanka": "mg/dL",
//    "Sudan": "mg/dL",
//    "Suriname": "mg/dL",
//    "Swaziland": "mg/dL",
//    "Sweden": "mmol/L",
//    "Switzerland": "mmol/L",
//    "Syria": "mg/dL",
//    "Taiwan": "mg/dL",
//    "Tajikistan": "mg/dL",
//    "Tanzania": "mg/dL",
//    "Thailand": "mg/dL",
//    "Timor-Leste": "mg/dL",
//    "Togo": "mg/dL",
//    "Tonga": "mg/dL",
//    "Trinidad and Tobago": "mg/dL",
//    "Tunisia": "mg/dL",
//    "Turkey": "mg/dL",
//    "Turkmenistan": "mg/dL",
//    "Tuvalu": "mg/dL",
//    "Uganda": "mg/dL",
//    "Ukraine": "mg/dL",
//    "United Arab Emirates": "mg/dL",
//    "United Kingdom": "mmol/L",
//    "United States": "mg/dL",
//    "Uruguay": "mg/dL",
//    "Uzbekistan": "mg/dL",
//    "Vanuatu": "mg/dL",
//    "Vatican City": "mmol/L",
//    "Venezuela": "mg/dL",
//    "Vietnam": "mg/dL",
//    "Yemen": "mg/dL",
//    "Zambia": "mg/dL",
//    "Zimbabwe": "mg/dL"
//]
